services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t php_nginx .
      - docker images
      - docker tag telegrambot kimbtechnologies/php_nginx:$TRAVIS_COMMIT
      - docker tag telegrambot kimbtechnologies/php_nginx:latest
      - docker push kimbtechnologies/php_nginx:$TRAVIS_COMMIT
      - docker push kimbtechnologies/php_nginx:latest