services:
  web:
    image: kimbtechnologies/php_nginx:latest
    container_name: php_nginx
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./php/:/php-code/ # load custom php code
      # - ./more-server-conf.conf:/etc/nginx/more-server-conf.conf:ro # add config options to the nginx conf (see file in repository for example)
      # - ./init.sh:/startup-before.sh # script to be run before php, nginx startup (e.g. for system updates, ..., runs as root)
    restart: unless-stopped