# please see file in readme
# this file is only for testing/ development

version: "2"

services:
  web:
    container_name: php_nginx
    ports:
      - "127.0.0.1:8080:80"
    build:
      args:
        #- BASEIMAGE_VERSION=7
        - BASEIMAGE_VERSION=8
      context: .
    volumes:
     - ./init.sh:/startup-before.sh